## Install and configure nginx reverse proxy and setup automatic 
## certificate generation and renewal with letsencrypt and dehydrated
## (Credit to Ian Allison of PIMS)
---
- name: Add acme (letsencrypt) user
  user: name={{ acme_user }}
        shell=/sbin/nologin
        home={{ acme_home }}

- name: Create letsencrypt directories
  file: path={{ item.name }} state=directory owner=root group={{ acme_user }} mode={{ item.mode }}
  with_items:
    - { name: "{{ acme_home }}",           mode: "0711" }
    - { name: "{{ acme_home }}/accounts",  mode: "0770" }
    - { name: "{{ acme_home }}/archive",   mode: "0770" }
    - { name: "{{ acme_home }}/certs",     mode: "0770" }
    - { name: "{{ acme_home }}/chains",    mode: "0770" }
    - { name: "{{ acme_home }}/challenge", mode: "0771" }

- name: Grab dehydrated repo
  ansible.builtin.git:
    repo: "{{ dehydrated_repo_url }}"
    dest: "{{ dehydrated_install_root }}"
    version: "{{ dehydrated_version }}"

- name: Collect letsencrypt config
  template: src={{ item.src }} dest={{ item.dest }} owner=root group={{ acme_user }} mode={{ item.mode }}
  with_items:
    - { src: "wrapper.j2", dest: "{{ acme_home }}/wrapper.sh",  mode: "0750" }
    - { src: "config.j2",  dest: "{{ acme_home }}/config.sh",   mode: "0640" }
    - { src: "domains.j2", dest: "{{ acme_home }}/domains.txt", mode: "0640" }
  notify:
    - Run dehydrate

- name: Add cron job
  file: src="{{ acme_home }}/wrapper.sh" dest="/etc/cron.daily/dehydrated-letsencrypt" state=link

- name: Create http location path if necessary
  file:
    path: "{{ nginx_conf_path }}/http-locations.d"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Create https location path if necessary
  file:
    path: "{{ nginx_conf_path }}/https-locations.d"
    state: directory
    owner: root
    group: root
    mode: "0755"

- name: Add nginx location handler for http
  template:
    src: acme-nginx.conf.j2
    dest: "{{ nginx_conf_path }}/http-locations.d/acme-nginx.conf"
  notify:
    - reload nginx

- name: Add nginx location handler for https
  template:
    src: acme-nginx.conf.j2
    dest: "{{ nginx_conf_path }}/https-locations.d/acme-nginx.conf"
  notify:
    - reload nginx

- name: Flush handlers for dehydrate
  ansible.builtin.meta: flush_handlers

