---
- name: Setup basic STAT environment
  hosts: r9
  become: true
  tasks:
    - name: Ensure hostname is set
      tags: ["hostname"]
      ansible.builtin.hostname:
        name: "{{ inventory_hostname }}"
    
    - name: Manage SSH public keys
      tags: ["ssh"]
      ansible.posix.authorized_key:
        user: "{{ item.value.user }}"
        state: "{{ item.value.state }}"
        key: "{{ item.value.public_key }}"
      with_dict: "{{ ssh_public_keys }}"
      when: ssh_public_keys is defined

    - name: Install base packages
      ansible.builtin.yum:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ base_packages }}"
      when: base_packages is defined

    - name: Register with UBC satellite
      ansible.builtin.shell:
        cmd: yum -y install --nogpgcheck http://satellite6.it.ubc.ca/pub/katello-ca-consumer-latest.noarch.rpm && subscription-manager register --org=UBCStatistics --activationkey=Rhel9_Stat_Migrate
      ignore_errors: true

    - name: Copy chrony config
      copy:
        src: '../files/chrony/chrony.conf'
        dest: '/etc/chrony.conf'
        force: true

    - name: Enable chrony
      ansible.builtin.shell: |
        systemctl start chronyd
        systemctl status chronyd
        systemctl enable chronyd
