---
- name: Apply hardening
  hosts: r9
  become: true
  tasks:
    - name: Install hardening packages
      ansible.builtin.yum:
        name: "{{ item.name }}"
        state: "{{ item.state | default('present') }}"
      with_items: "{{ hardening_packages }}"
      when: hardening_packages is defined

    - name: Setup fail2ban filtered SSH service
      copy:
        src: ../files/fail2ban/sshd.local
        dest: /etc/fail2ban/jail.d/sshd.local
        force: true

    - name: Enable fail2ban
      ansible.builtin.service:
        name: fail2ban
        enabled: true
        state: started

    - name: Initialize aide
      ansible.builtin.shell: |
        aide --init
        mv /var/lib/aide/aide.db.new.gz /var/lib/aide/aide.db.gz
    
    - name: CRON job for integrity check
      ansible.builtin.cron:
        name: AIDE integrity check
        job: /usr/sbin/aide --check
        hour: 4
        weekday: 6

    - name: Disable root login
      ansible.builtin.lineinfile:
            dest: /etc/ssh/sshd_config
            regexp: '^PermitRootLogin'
            line: "PermitRootLogin no"
            state: present
            backup: yes

    - name: Restart ssh
      ansible.builtin.service:
        name: sshd
        state: restarted

    - name: Copy sysctl.conf with IP hardening rules
      copy:
        src: ../files/sysctl.conf
        dest: /etc/sysctl.conf
        force: true


    