---
- name: Remove existing certs
  file:
    path: '~{{ acme_user }}/certs/{{ inventory_hostname }}/'
    state: absent

- name: Run dehydrate
  shell: '~{{ acme_user }}/wrapper.sh'
  failed_when: False

- name: reload nginx
  ansible.builtin.service:
    name: nginx
    state: restarted